version: '3.8'  # Use version 3.8 or higher, which is suitable for most cases
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    ## run init.sql 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../data/timescaledb:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    container_name: fastapi-redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"

